name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          rubygems: latest

      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    name: test (ruby=${{ matrix.ruby }}, grape=${{ matrix.grape }}, grape-swagger=${{ matrix.grape_swagger}}, grape_entity=${{ matrix.grape_entity }})
    strategy:
      matrix:
        include:
          # Ruby 3.1 combinations
          - ruby: '3.0'
            grape: '~> 2.0.0'
            grape_swagger: '~> 2.0.3'
            grape_entity: '~> 1.0.1'
          - ruby: '3.0'
            grape: '~> 2.0.0'
            grape_swagger: '~> 2.1.1'
            grape_entity: 'head'

          # Ruby 3.4 combinations
          - ruby: '3.4'
            grape: '~> 2.0.0'
            grape_swagger: '~> 2.0.3'
            grape_entity: '~> 1.0.1'
          - ruby: '3.4'
            grape: '~> 2.0.0'
            grape_swagger: '~> 2.0.3'
            grape_entity: 'head'
          - ruby: '3.4'
            grape: '~> 2.0.0'
            grape_swagger: 'head'
            grape_entity: '~> 1.0.1'
          - ruby: '3.4'
            grape: '~> 2.0.0'
            grape_swagger: 'head'
            grape_entity: 'head'
          - ruby: '3.4'
            grape: 'head'
            grape_swagger: 'head'
            grape_entity: '~> 1.0.1'
          - ruby: '3.4'
            grape: 'head'
            grape_swagger: 'head'
            grape_entity: 'head'

          # Ruby head combinations
          - ruby: 'head'
            grape: '~> 2.0.0'
            grape_swagger: '~> 2.0.3'
            grape_entity: '~> 1.0.1'
          - ruby: 'head'
            grape: '~> 2.0.0'
            grape_swagger: '~> 2.0.3'
            grape_entity: 'head'
          - ruby: 'head'
            grape: '~> 2.0.0'
            grape_swagger: 'head'
            grape_entity: '~> 1.0.1'
          - ruby: 'head'
            grape: '~> 2.0.0'
            grape_swagger: 'head'
            grape_entity: 'head'

          # - ruby: 'head'
          #   grape: 'head'
          #   grape_swagger: 'head'
          #   grape_entity: '~> 1.0.1'
          # - ruby: 'head'
          #   grape: 'head'
          #   grape_swagger: 'head'
          #   grape_entity: 'head'

    runs-on: ubuntu-latest
    env:
      GRAPE_VERSION: ${{ matrix.grape }}
      GRAPE_SWAGGER_VERSION: ${{ matrix.grape_swagger }}
      GRAPE_ENTITY_VERSION: ${{ matrix.grape_entity }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake spec
