name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true
          rubygems: latest

      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    name: test (ruby=${{ matrix.ruby }}, grape=${{ matrix.grape }}, grape-swagger=${{ matrix.grape_swagger}}, grape_entity=${{ matrix.grape_entity }})
    strategy:
      matrix:
        grape: [ '~> 2.0.0', 'head' ]
        grape_swagger: [ '~> 2.0.3', 'head' ]
        grape_entity: [ '~> 1.0.1', 'head' ]
        ruby: [ '3.0', '3.4', 'head' ]
        # Exclude combinations that are not supported.
        exclude:
          - { grape_swagger: '~> 2.0.3', grape: 'head' }
    runs-on: ubuntu-latest
    env:
      GRAPE_VERSION: ${{ matrix.grape }}
      GRAPE_SWAGGER_VERSION: ${{ matrix.grape_swagger }}
      GRAPE_ENTITY_VERSION: ${{ matrix.grape_entity }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake spec
